python generate_samples.py \
  --data_dir=/'/home/ll2948/musicGan/ptb' \
  --data_set=ptb \
  --batch_size=20 \
  --sequence_length=500 \
  --base_directory='/home/ll2948/musicGan/log' \
  --hparams="gen_rnn_size=32,dis_rnn_size=32,gen_num_layers=2,gen_vd_keep_prob=1.0" \
  --generator_model='seq2seq_vd' \
  --discriminator_model='seq2seq_vd' \
  --is_present_rate=0.75 \
  --maskgan_ckpt='/home/ll2948/musicGan/log/train/model.ckpt-30890' \
  --seq2seq_share_embedding=True \
  --dis_share_embedding=True \
  --attention_option=luong \
  --mask_strategy=random \
  --baseline_method=critic \
  --number_epochs=4
